"""empty message

Revision ID: 50b07f0e0f47
Revises: d66e2fc89ac4
Create Date: 2023-11-22 15:04:00.462936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b07f0e0f47'
down_revision = 'd66e2fc89ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.Integer(), nullable=False))
        batch_op.drop_constraint('course_school_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'school', ['school'], ['id'])
        batch_op.drop_column('school_id')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('course', sa.Integer(), nullable=False))
        batch_op.drop_constraint('enrollment_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('enrollment_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student'], ['id'])
        batch_op.create_foreign_key(None, 'course', ['course'], ['id'])
        batch_op.drop_column('student_id')
        batch_op.drop_column('course_id')

    with op.batch_alter_table('gpa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student', sa.Integer(), nullable=False))
        batch_op.drop_constraint('gpa_student_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'student', ['student'], ['id'])
        batch_op.drop_column('student_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.Integer(), nullable=False))
        batch_op.drop_constraint('student_school_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'school', ['school'], ['id'])
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_school_id_fkey', 'school', ['school_id'], ['id'])
        batch_op.drop_column('school')

    with op.batch_alter_table('gpa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('gpa_student_id_fkey', 'student', ['student_id'], ['id'])
        batch_op.drop_column('student')

    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('enrollment_student_id_fkey', 'student', ['student_id'], ['id'])
        batch_op.create_foreign_key('enrollment_course_id_fkey', 'course', ['course_id'], ['id'])
        batch_op.drop_column('course')
        batch_op.drop_column('student')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('course_school_id_fkey', 'school', ['school_id'], ['id'])
        batch_op.drop_column('school')

    # ### end Alembic commands ###
