"""empty message

Revision ID: d66e2fc89ac4
Revises: 5cfbd2e74561
Create Date: 2023-11-22 14:41:45.372820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66e2fc89ac4'
down_revision = '5cfbd2e74561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=True))
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('contact_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('user',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('contact')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
